var tekkenNames = [
      'Alex'
    , 'Alisa Bosconovitch'
    , 'Ancient Ogre'
    , 'Angel'
    , 'Anna Williams'
    , 'Armor King I'
    , 'Armor King II'
    , 'Asuka Kazama'
    , 'Azazel'
    , 'Baek Doo San'
    , 'Bob Richards'
    , 'Bruce Irvin'
    , 'Bryan Fury'
    , 'Christie Monteiro'
    , 'Claudio Serafino'
    , 'Combot'
    , 'Craig Marduk'
    , 'Crow'
    , 'Devil Kazuya'
    , 'Devil Jin'
    , 'Devil Kazumi'
    , 'Dr. Bosconovitch'
    , 'Eddy Gordo'
    , 'Feng Wei'
    , 'Forest Law'
    , 'Ganryu'
    , 'Gigas'
    , 'Gon'
    , 'Gun Jack'
    , 'Heihachi Mishima'
    , 'Hwoarang'
    , 'Jin Kazama'
    , 'Jinpachi Mishima'
    , 'Josie Rizal'
    , 'Julia Chang'
    , 'Jun Kazama'
    , 'Katarina Alves'
    , 'Kazumi Mishima'
    , 'Kazuya Mishima'
    , 'King I'
    , 'King II'
    , 'Kumar I'
    , 'Kuma II'
    , 'Kunimitsu'
    , 'Lars Alexandersson'
    , 'Lee Chaolan'
    , 'Lei Wulong'
    , 'Leo Kliesen'
    , 'Lili De Rochefort'
    , 'Ling Xiaoyu'
    , 'Lucky Chloe'
    , 'Marshall Law'
    , 'Michelle Chang'
    , 'Miguel Caballero Rojo'
    , 'Miharu Hirano'
    , 'Mokujin'
    , 'NANCY-MI847J'
    , 'Nina Williams'
    , 'Panda'
    , 'Paul Phoenix'
    , 'Prototype Jack'
    , 'Raven'
    , 'Roger'
    , 'Roger Jr.'
    , 'Shaheen'
    , 'Sebastian'
    , 'Sergei Dragunov'
    , 'Slim Bob'
    , 'Steve Fox'
    , 'Tiger Jackson'
    , 'True Ogre'
    , 'Violet'
    , 'Wang Jinrei'
    , 'Yoshimitsu'
    , 'Zafina'
    , 'Alex'
    , 'Alisa Bosconovitch'
    , 'Ancient Ogre'
    , 'Angel'
    , 'Anna Williams'
    , 'Asuka Kazama'
    , 'Baek Doo San'
    , 'Bob Richards'
    , 'Bruce Irvin'
    , 'Bryan Fury'
    , 'Christie Monteiro'
    , 'Combot'
    , 'Craig Marduk'
    , 'Crow'
    , 'Devil/Devil Kazuya'
    , 'Devil Jin'
    , 'Dr. Bosconovitch'
    , 'Eddy Gordo'
    , 'Eliza'
    , 'Feng Wei'
    , 'Forest Law'
    , 'Ganryu'
    , 'Gun Jack'
    , 'Heihachi Mishima'
    , 'Hwoarang'
    , 'Jaycee'
    , 'Jin Kazama'
    , 'Jinpachi Mishima'
    , 'Julia Chang'
    , 'Jun Kazama'
    , 'Kazuya Mishima'
    , 'King II'
    , 'Kinjin'
    , 'Kuma II'
    , 'Kunimitsu'
    , 'Lars Alexandersson'
    , 'Lee Chaolan'
    , 'Lei Wulong'
    , 'Leo Kliesen'
    , 'Lili De Rochefort'
    , 'Ling Xiaoyu'
    , 'Marshall Law'
    , 'Michelle Chang'
    , 'Miguel Caballero Rojo'
    , 'Miharu Hirano'
    , 'Mokujin'
    , 'Nina Williams'
    , 'Panda'
    , 'Paul Phoenix'
    , 'Prototype Jack'
    , 'Roger'
    , 'Roger Jr.'
    , 'Sebastian'
    , 'Sergei Dragunov'
    , 'Slim Bob'
    , 'Steve Fox'
    , 'Tetsujin'
    , 'Tiger Jackson'
    , 'True Ogre'
    , 'Violet'
    , 'Wang Jinrei'
    , 'Yoshimitsu'
    , 'Zafina'
    , 'Alisa Bosconovitch'
    , 'Ancient Ogre'
    , 'Anna Williams'
    , 'Armor King I/II'
    , 'Asuka Kazama'
    , 'Baek Doo San'
    , 'Bob Richards'
    , 'Bruce Irvin'
    , 'Bryan Fury'
    , 'Christie Monteiro'
    , 'Craig Marduk'
    , 'Devil/Devil Kazuya'
    , 'Devil Jin'
    , 'Dr. Bosconovitch'
    , 'Eddy Gordo'
    , 'Feng Wei'
    , 'Forest Law'
    , 'Ganryu'
    , 'Gun Jack'
    , 'Heihachi Mishima'
    , 'Hwoarang'
    , 'Jin Kazama'
    , 'Julia Chang'
    , 'Kazuya Mishima'
    , 'King II'
    , 'Kuma II'
    , 'Lars Alexandersson'
    , 'Lee Chaolan'
    , 'Lei Wulong'
    , 'Leo Kliesen'
    , 'Lili De Rochefort'
    , 'Ling Xiaoyu'
    , 'Marshall Law'
    , 'Miguel Caballero Rojo'
    , 'Mokujin'
    , 'Nina Williams'
    , 'Panda'
    , 'Paul Phoenix'
    , 'Prototype Jack'
    , 'Raven'
    , 'Roger Jr.'
    , 'Sergei Dragunov'
    , 'Steve Fox'
    , 'Wang Jinrei'
    , 'Yoshimitsu'
    , 'Zafina'
];

module.exports = {
    characters : function() {
        return tekkenNames;
    },
    name : function() {
        var l = this.characters.length-1;
        return this.characters[ Math.floor( Math.random() * l ) ];
    }
};
